name: Run tests on pull request
on:
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execution permission forgradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew clean testDebug